### ISSUE TITLE
 have purchased this machine in china in 2019 from factory and got delivered in ghungzou and then got shippment locally to pakistan , i have tested it yesterday  , it is not producing 3d form , when i am printing the block it produce which is not solid , what should i do

### ISSUE THREAD

**Issue by k3g1397** [Photonsters/anycubic-photon-docs#20]
have purchased this machine in china in 2019 from factory and got delivered in ghungzou and then got shippment locally to pakistan , i have tested it yesterday  , it is not producing 3d form , when i am printing the block it produce which is not solid , what should i do

half block remains with upside and half on downside , it breaks while printing block

![3408e6e2-dbb3-4622-bdb5-93e31af8235c](https://user-images.githubusercontent.com/49635942/56116537-834f2c00-5f7f-11e9-8ccc-94a5cf04ec10.jpg)
![IMG_6257](https://user-images.githubusercontent.com/49635942/56116538-834f2c00-5f7f-11e9-995f-16b7e7c703ab.jpg)
![IMG_6258](https://user-images.githubusercontent.com/49635942/56116539-83e7c280-5f7f-11e9-99c0-a6f435534563.jpg)
![IMG_6259](https://user-images.githubusercontent.com/49635942/56116540-83e7c280-5f7f-11e9-86e7-f358aa6cbcff.jpg)
![IMG_6260](https://user-images.githubusercontent.com/49635942/56116541-83e7c280-5f7f-11e9-92cd-9b673d703119.jpg)

**Comment by Sailormaine** [comment]
This is my theory - no guarantees, but it might help.

I think that the resin that Anycubic is providing with the machine has changed, but the demo file has not.  I think it needs a bit more exposure.

Start the demo file again.  As soon as you have started it, press the little gear icon on the bottom right of the touch screen.  Edit the bottom setting - I think it's called "normal exposure" - and raise the value by 2 to 4 seconds.  Then click the checkmark icon and then the return icon to bring you back to the regular screen.  

Let's see how well that works.

**Comment by k3g1397** [comment]
Ok ill do it

**Comment by X3msnake** [comment]
This type os questions should be placed ate fb group not here
https://www.facebook.com/groups/AnycubicPhoton/
