### ISSUE TITLE
How to control curing time for each layers independently?

### ISSUE THREAD

**Issue by bibekraut** [Photonsters/anycubic-photon-docs#24]
I want to use two different resins. Cure one partially with one and then another with a different color. Since curing time for each resin is different, I need a way to control the curing height and curing time for each layer independently. I tried 010 Editor, but could only modify the height of each layer. Is there any hack for independent control of curing time and curing height?

**Comment by X3msnake** [comment]
forget hacking the file it cannot be done. values are hardcoded and use the first header so untill CBD and Anycubic comes out with a firmware that allows individuall layer settings you are shit out of luck.

that said you are thinking this the wrong way. just pause the file at the layer height you wsnt to change vats. enter the settings menu during the print and change normal layer time. put you new vat in. be carefull not to drip resin onto the screen and have fun
