### ISSUE TITLE
How to make shorter supports?

### ISSUE THREAD

**Issue by Teddyz** [Photonsters/anycubic-photon-docs#28]
Is there any reason it is not possible to make the supports shorter than 3.5mm? I see no reason to waste printing-time making them taller than 1mm. Or is there a good reason for this limitation?

**Comment by senkunmusashi** [comment]
The reason supports need to be a minimum distance from the build plate is to prevent pooling and curing of resin. 5mm is barely adequate to allow resin flow and refresh, 1mm and you'll get a mess of a cured resin block at the bottom of your print.
