### ISSUE TITLE
Does a comparison fit here

### ISSUE THREAD

**Issue by NardJ** [Photonsters/anycubic-photon-docs#4]
I am wondering if a comparison between the photon and other similar priced printers has a place here?

http://www.pandarve.link/DLPSLAComparison/Comparison.html

**Comment by X3msnake** [comment]
Yes this would be a good info to have.

We might need to work on the info a bit, it needs to be more consistente across printers to be a good comparison. but you can submit the HTML to the git.

What folder would be the best for this type of info?

**Comment by NardJ** [comment]
Maybe a new folder named something like a "Buying guide"? This could also include accessories to buy along with your Photon?

**Comment by NardJ** [comment]
@X3msnake Added a new folder Comparison and placed the files there. Not sure how to change the folder name, will look into that.

**Comment by X3msnake** [comment]
PDF or SVG

**Comment by NardJ** [comment]
Added the PDF

**Comment by NardJ** [comment]
Reformatted to 1 page

**Comment by X3msnake** [comment]
i have merged this with the master branch ;)
