### ISSUE TITLE
Turning off touchscreen

### ISSUE THREAD

**Issue by luizribeiro** [Photonsters/anycubic-photon-docs#49]
Is anyone aware of any gcodes for turning off the touchscreen?

I'm working on a web-based controller for the Elegoo Mars (which often has similarities to the Photon). One of the things that I would like to be able to do is turn off the touchscreen - which seems to be on all the time even if I use `M8085 T0` or `M8085 T5` (the "screen saver time" command, which just makes the printer show the logo as a "screen saver").

**Comment by X3msnake** [comment]
AFIK there is no way to turn the screen off via gcode.
