### ISSUE TITLE
Photon Workshop 2.1.23RC8 - Crashes often but not always when opening scene file

### ISSUE THREAD

**Issue by tlhintoq** [Photonsters/anycubic-photon-docs#50]
What more can be said that's not in the title?
Easily 75% of the time when I open a .scene file Photon Workshop crashes and evaporates without a message or dialog.
Reopen the program
Reopen the .scene - now its fine.

**Comment by X3msnake** [comment]
We are not affiliated with Anycubic nor have we been involved with the development of Porkshop

You should contact anycubic
