### ISSUE TITLE
Photon Workshop 2.1.23RC8 - Can't drag windo higher than top boundary of primary monitor

### ISSUE THREAD

**Issue by tlhintoq** [Photonsters/anycubic-photon-docs#51]
Let's say you have a couple monitors - maybe a second monitor on your laptop.
And monitor #2 is above #1
You can't drag Photon Workshop from the lower monitor to the upper monitor because the app stops itself from dragging.
Trying to get fancy by making your own border and title bar etc. is stopping the window from just behaving normally and as expected.

**Comment by X3msnake** [comment]
Why are you posting a issue you have with Photon Porkshop here?

We are not affiliated with Anycubic nor have we been involved with the development of Porkshop

You should contact anycubic
